# Generated by Django 5.2.3 on 2025-06-16 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spradar_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'conference',
            },
        ),
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spradar_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'franchise',
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spradar_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spradar_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=35)),
                ('country', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('capacity', models.IntegerField()),
                ('surface', models.CharField(max_length=50)),
                ('roof_type', models.CharField(max_length=50)),
                ('sr_id', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spradar_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conference')),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.AddField(
            model_name='conference',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.league'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spradar_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('sr_id', models.CharField(max_length=100)),
                ('founded', models.IntegerField()),
                ('owner', models.CharField(max_length=200)),
                ('general_manager', models.CharField(max_length=200)),
                ('championships_won', models.IntegerField()),
                ('conference_titles', models.IntegerField()),
                ('division_titles', models.IntegerField()),
                ('playoff_appearances', models.IntegerField()),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.division')),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.franchise')),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
