# Generated by Django 5.2.3 on 2025-06-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='championship_seasons',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
