# Generated by Django 5.2.3 on 2025-06-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_team_championship_seasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='mascot',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
