# Generated by Django 5.2.3 on 2025-06-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_mascot'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='standings',
            field=models.JSONField(default=dict),
        ),
    ]
