# Generated by Django 5.2.3 on 2025-06-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_team_standings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='standings',
        ),
        migrations.AddField(
            model_name='league',
            name='standings',
            field=models.JSONField(default=dict),
        ),
    ]
