"""
Django settings for griddy project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os

from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h8#kng_6l7e0ub5ak)_ktf%1i0su2kv*jxzo+6w433mp%&%vt+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    "django_extensions",
    "core"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'griddy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'griddy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': "griddy",
        'USER': "postgres",
        'PASSWORD': "postgres",
        'HOST': os.getenv("POSTGRES_HOST"),
        'PORT': "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#### Begin custom/griddy specific settings ####
# TODO: This is just for playing locally.
# A more robust solution is to use something like Selenium to generate the cookies
# And get this info from there
FIREFOX_COOKIES_DB = os.getenv("FIREFOX_COOKIES_DB")

SPORTRADAR_API_KEY = os.getenv("SPORTRADAR_API_KEY")
SPORTRADAR_API_BASE_URL = os.getenv("SPORTRADAR_API_BASE_URL")

NFL_AUTH_REQ_HEADERS_FILE = Path(BASE_DIR, 'example_data/nfl_auth_req_headers.json')
NFL_API_REQ_HEADERS_FILE = Path(BASE_DIR, 'example_data/nfl_api_req_headers.json')

NFL_AUTH_URL = os.getenv("NFL_AUTH_URL")
NFL_API_BASE_URL = os.getenv("NFL_API_BASE_URL")
NFL_PRO_LOGIN_URL = os.getenv("NFL_PRO_LOGIN_URL")
NFL_PRO_EMAIL = os.getenv("NFL_PRO_EMAIL")
NFL_PRO_PASSWORD = os.getenv("NFL_PRO_PASSWORD")

NFL_CLIENT_KEY = os.getenv("NFL_CLIENT_KEY")
NFL_CLIENT_SECRET = os.getenv("NFL_CLIENT_SECRET")
NFL_DEVICE_ID = os.getenv("NFL_DEVICE_ID")
NFL_DEVICE_INFO = os.getenv("NFL_DEVICE_INFO")
NFL_NETWORK_TYPE = os.getenv("NFL_NETWORK_TYPE")
